# Usar una imagen base de Node.js
FROM node:17

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el package.json y el package-lock.json
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Instalar serve globalmente en el contenedor
RUN npm install -g serve

# Copiar el resto de los archivos
COPY . .

# Construir la aplicación
RUN npm run build

# Exponer el puerto 3005
EXPOSE 3005

# Iniciar la aplicación
CMD ["serve", "-s", "build"]

